/**
 * MigrationMap - Export Generators
 * Production-ready redirect configurations for Next.js, Vercel, Netlify, Apache, Nginx, CSV, JSON, Markdown.
 */

import { UrlMapping, ExportOptions } from '../types/migration';
import { getCleanExportPath } from '../utils/url';

export interface ExportResult {
  code: string;
  filename: string;
  mimeType: string;
  count: number;
  warnings: string[];
}

/**
 * Filters mappings based on export options
 */
export function getExportableMappings(
  mappings: UrlMapping[],
  options: ExportOptions,
  allowEmptyDestination = false
): UrlMapping[] {
  return mappings.filter(m => {
    if (!allowEmptyDestination && !m.newUrl) return false;
    if (options.includeStatus && options.includeStatus.length > 0 && !options.includeStatus.includes(m.status)) {
      return false;
    }
    return true;
  });
}

/**
 * Generates CSV Export (preserves every single mapping in the project)
 */
export function exportToCsv(mappings: UrlMapping[], options: ExportOptions): ExportResult {
  const exportable = getExportableMappings(mappings, options, true);
  const warnings: string[] = [];

  const headers = ['old_url', 'new_url', 'confidence', 'status', 'match_reason'];
  const rows = [headers.join(',')];

  for (const m of exportable) {
    if (m.confidence < 50 && m.newUrl && options.includeLowConfidenceWarnings) {
      warnings.push(`Low confidence (${m.confidence}%): ${m.oldUrl} → ${m.newUrl}`);
    }

    const row = [
      escapeCsv(m.oldUrl),
      escapeCsv(m.newUrl || ''),
      m.confidence.toString(),
      escapeCsv(m.status),
      escapeCsv(m.explanation?.primaryReason || (m.newUrl ? 'Suggested match' : 'No destination mapped')),
    ];
    rows.push(row.join(','));
  }

  return {
    code: rows.join('\n'),
    filename: 'migration-redirects.csv',
    mimeType: 'text/csv',
    count: exportable.length,
    warnings,
  };
}

export function escapeCsv(rawField: string): string {
  if (!rawField) return '';
  let field = rawField;
  
  // Prevent Spreadsheet Formula Injection (CSV DDE)
  // If field starts with =, +, -, @, tab, or carriage return, prepend single quote
  if (/^[\=\+\-\@\t\r]/.test(field)) {
    field = `'${field}`;
  }

  if (field.includes(',') || field.includes('"') || field.includes('\n') || field.includes('\r')) {
    return `"${field.replace(/"/g, '""')}"`;
  }
  return field;
}

/**
 * Generates JSON Export
 */
export function exportToJson(mappings: UrlMapping[], options: ExportOptions): ExportResult {
  const exportable = getExportableMappings(mappings, options, true);
  const warnings: string[] = [];

  const output = {
    project: {
      generator: 'MigrationMap',
      version: '1.0.0',
      exportedAt: new Date().toISOString(),
      statusCode: options.statusCode,
      totalRedirects: exportable.length,
    },
    redirects: exportable.map(m => {
      if (m.confidence < 50 && options.includeLowConfidenceWarnings) {
        warnings.push(`Low confidence (${m.confidence}%): ${m.oldUrl}`);
      }
      return {
        source: m.oldUrl,
        destination: m.newUrl,
        statusCode: options.statusCode,
        confidence: m.confidence,
        status: m.status,
        matchReason: m.explanation.primaryReason,
        signals: m.explanation.summaryPoints,
      };
    }),
  };

  return {
    code: JSON.stringify(output, null, 2),
    filename: 'migration-redirects.json',
    mimeType: 'application/json',
    count: exportable.length,
    warnings,
  };
}

/**
 * Generates Markdown Migration Report
 */
export function exportToMarkdown(mappings: UrlMapping[], options: ExportOptions): ExportResult {
  const exportable = getExportableMappings(mappings, options, true);
  const warnings: string[] = [];

  const approvedCount = exportable.filter(m => m.status === 'approved' || m.status === 'manually_mapped').length;
  const suggestedCount = exportable.filter(m => m.status === 'suggested').length;
  const needsReviewCount = exportable.filter(m => m.status === 'needs_review').length;
  const avgConfidence = exportable.length > 0
    ? Math.round(exportable.reduce((acc, m) => acc + m.confidence, 0) / exportable.length)
    : 0;

  const lines: string[] = [
    '# Website Migration Redirect Report',
    '',
    `*Generated by MigrationMap on ${new Date().toLocaleDateString()}*`,
    '',
    '## Executive Summary',
    '',
    `- **Total Exported Rules:** ${exportable.length}`,
    `- **Average Confidence:** ${avgConfidence}%`,
    `- **Approved / Manually Mapped:** ${approvedCount}`,
    `- **Suggested (Unreviewed):** ${suggestedCount}`,
    `- **Flagged For Review:** ${needsReviewCount}`,
    `- **HTTP Status Code:** ${options.statusCode} (${options.statusCode === 301 ? 'Permanent' : 'Temporary'})`,
    '',
    '## Redirect Mappings Table',
    '',
    '| Old URL | New Destination | Confidence | Status | Reason |',
    '| :--- | :--- | :---: | :--- | :--- |',
  ];

  for (const m of exportable) {
    if (m.confidence < 50 && options.includeLowConfidenceWarnings) {
      warnings.push(`Low confidence match: ${m.oldUrl}`);
    }
    const cleanOld = m.oldUrl.replace(/\|/g, '\\|');
    const cleanNew = (m.newUrl || '').replace(/\|/g, '\\|');
    lines.push(`| \`${cleanOld}\` | \`${cleanNew}\` | **${m.confidence}%** | \`${m.status}\` | ${m.explanation.primaryReason} |`);
  }

  lines.push('', '---', '*Generated by [MigrationMap](https://migrationmap.dev) - Deterministic Website Redirect Engine*');

  return {
    code: lines.join('\n'),
    filename: 'migration-report.md',
    mimeType: 'text/markdown',
    count: exportable.length,
    warnings,
  };
}

/**
 * Generates Next.js redirects configuration
 */
export function exportToNextJs(mappings: UrlMapping[], options: ExportOptions): ExportResult {
  const exportable = getExportableMappings(mappings, options);
  const warnings: string[] = [];

  const permanent = options.statusCode === 301 || options.statusCode === 308;

  const redirectObjects = exportable.map(m => {
    const srcPath = m.oldNormalized ? getCleanExportPath(m.oldNormalized) : m.oldUrl;
    const dstPath = m.newNormalized ? getCleanExportPath(m.newNormalized) : m.newUrl!;

    if (m.confidence < 50 && options.includeLowConfidenceWarnings) {
      warnings.push(`Low confidence (${m.confidence}%): ${srcPath} → ${dstPath}`);
    }

    return `      {
        source: '${srcPath.replace(/'/g, "\\'")}',
        destination: '${dstPath.replace(/'/g, "\\'")}',
        permanent: ${permanent},
      }`;
  });

  const code = `/**
 * Next.js Redirects Configuration
 * Place inside your next.config.js or next.config.mjs
 * Generated by MigrationMap (${exportable.length} rules)
 */

/** @type {import('next').NextConfig} */
const nextConfig = {
  async redirects() {
    return [
${redirectObjects.join(',\n')}
    ];
  },
};

module.exports = nextConfig;
`;

  return {
    code,
    filename: 'next.config.js',
    mimeType: 'application/javascript',
    count: exportable.length,
    warnings,
  };
}

/**
 * Generates Vercel vercel.json
 */
export function exportToVercel(mappings: UrlMapping[], options: ExportOptions): ExportResult {
  const exportable = getExportableMappings(mappings, options);
  const warnings: string[] = [];
  const permanent = options.statusCode === 301 || options.statusCode === 308;

  const vercelConfig = {
    $schema: 'https://openapi.vercel.sh/vercel.json',
    redirects: exportable.map(m => {
      const srcPath = m.oldNormalized ? getCleanExportPath(m.oldNormalized) : m.oldUrl;
      const dstPath = m.newNormalized ? getCleanExportPath(m.newNormalized) : m.newUrl!;

      if (m.confidence < 50 && options.includeLowConfidenceWarnings) {
        warnings.push(`Low confidence (${m.confidence}%): ${srcPath} → ${dstPath}`);
      }

      return {
        source: srcPath,
        destination: dstPath,
        permanent,
      };
    }),
  };

  return {
    code: JSON.stringify(vercelConfig, null, 2),
    filename: 'vercel.json',
    mimeType: 'application/json',
    count: exportable.length,
    warnings,
  };
}

/**
 * Generates Netlify _redirects file
 */
export function exportToNetlify(mappings: UrlMapping[], options: ExportOptions): ExportResult {
  const exportable = getExportableMappings(mappings, options);
  const warnings: string[] = [];
  const statusCode = options.statusCode;

  const lines = [
    '# Netlify Redirects File',
    '# Place in your public/ or build publish directory as "_redirects"',
    `# Total rules: ${exportable.length}`,
    '',
  ];

  for (const m of exportable) {
    const srcPath = m.oldNormalized ? getCleanExportPath(m.oldNormalized) : m.oldUrl;
    const dstPath = m.newNormalized ? getCleanExportPath(m.newNormalized) : m.newUrl!;

    if (m.confidence < 50 && options.includeLowConfidenceWarnings) {
      warnings.push(`Low confidence (${m.confidence}%): ${srcPath}`);
    }

    // Pad paths for readability
    const paddedSrc = srcPath.padEnd(Math.max(35, srcPath.length + 2));
    const paddedDst = dstPath.padEnd(Math.max(35, dstPath.length + 2));
    lines.push(`${paddedSrc} ${paddedDst} ${statusCode}!`);
  }

  return {
    code: lines.join('\n'),
    filename: '_redirects',
    mimeType: 'text/plain',
    count: exportable.length,
    warnings,
  };
}

/**
 * Generates Apache .htaccess RewriteRules
 */
export function exportToApache(mappings: UrlMapping[], options: ExportOptions): ExportResult {
  const exportable = getExportableMappings(mappings, options);
  const warnings: string[] = [];
  const statusCode = options.statusCode;

  const lines = [
    '# Apache .htaccess Redirect Rules',
    '# Generated by MigrationMap',
    `<IfModule mod_rewrite.c>`,
    'RewriteEngine On',
    'RewriteBase /',
    '',
  ];

  for (const m of exportable) {
    const srcPath = m.oldNormalized ? getCleanExportPath(m.oldNormalized) : m.oldUrl;
    const dstPath = m.newNormalized ? getCleanExportPath(m.newNormalized) : m.newUrl!;

    if (m.confidence < 50 && options.includeLowConfidenceWarnings) {
      warnings.push(`Low confidence (${m.confidence}%): ${srcPath}`);
    }

    // Strip leading slash for RewriteRule match pattern
    const regexPattern = `^${srcPath.replace(/^\//, '').replace(/\./g, '\\.')}$`;
    lines.push(`RewriteRule ${regexPattern} ${dstPath} [R=${statusCode},L]`);
  }

  lines.push('</IfModule>');

  return {
    code: lines.join('\n'),
    filename: '.htaccess',
    mimeType: 'text/plain',
    count: exportable.length,
    warnings,
  };
}

/**
 * Generates Nginx configuration block
 */
export function exportToNginx(mappings: UrlMapping[], options: ExportOptions): ExportResult {
  const exportable = getExportableMappings(mappings, options);
  const warnings: string[] = [];
  const statusCode = options.statusCode;

  const lines = [
    '# Nginx Redirect Configuration Snippet',
    '# Place inside your server {} block in /etc/nginx/sites-available/',
    `# Total rules: ${exportable.length}`,
    '',
  ];

  for (const m of exportable) {
    const srcPath = m.oldNormalized ? getCleanExportPath(m.oldNormalized) : m.oldUrl;
    const dstPath = m.newNormalized ? getCleanExportPath(m.newNormalized) : m.newUrl!;

    if (m.confidence < 50 && options.includeLowConfidenceWarnings) {
      warnings.push(`Low confidence: ${srcPath}`);
    }

    lines.push(`location = ${srcPath} {`);
    lines.push(`    return ${statusCode} ${dstPath};`);
    lines.push('}');
  }

  return {
    code: lines.join('\n'),
    filename: 'nginx-redirects.conf',
    mimeType: 'text/plain',
    count: exportable.length,
    warnings,
  };
}

/**
 * Universal dispatcher
 */
export function generateExport(
  format: ExportOptions['format'],
  mappings: UrlMapping[],
  options: ExportOptions
): ExportResult {
  switch (format) {
    case 'csv':
      return exportToCsv(mappings, options);
    case 'json':
      return exportToJson(mappings, options);
    case 'markdown':
      return exportToMarkdown(mappings, options);
    case 'nextjs':
      return exportToNextJs(mappings, options);
    case 'vercel':
      return exportToVercel(mappings, options);
    case 'netlify':
      return exportToNetlify(mappings, options);
    case 'apache':
      return exportToApache(mappings, options);
    case 'nginx':
      return exportToNginx(mappings, options);
    default:
      return exportToCsv(mappings, options);
  }
}
